### ISSUE TITLE
[REQUEST] Node Support

### ISSUE THREAD

**Issue by sasial-dev** [lukasbach/monaco-editor-auto-typings#14]
**Is your feature request related to a problem? Please describe.**
I'm unable to import packages that have a (dependency or have a) `node:` prefix, and I want to be able to use node globals.

**Describe the solution you'd like**
* Support for node globals
* Support for importing from `node:` preifx
* An option in the config to toggle the node-env

**Additional context**
N/A

**Comment by sasial-dev** [comment]
This would also allow me to import node-only libraries such as `discord.js`

**Comment by lukasbach** [comment]
Hi @sasial-dev, thanks for the suggestion. You should be able to manually load node.js types by adding to the [version option](https://lukasbach.github.io/monaco-editor-auto-typings/docs/interfaces/Options.html#versions), i.e. with

```ts
{
  versions: {
    "@types/node": "17.0.38"
  }
}
```

**Comment by sasial-dev** [comment]
I tried that, but it's not recognising the modules still!

`import { CommandInteraction } from "discord.js"`

> Error other than 404 while fetching from Unpkg at https://unpkg.com/node:child_process/package.json
Error other than 404 while fetching from Unpkg at https://unpkg.com/node:events/package.json
Error other than 404 while fetching from Unpkg at https://unpkg.com/node:https/package.json
Error other than 404 while fetching from Unpkg at https://unpkg.com/node:stream/package.json
Error other than 404 while fetching from Unpkg at https://unpkg.com/node:worker_threads/package.json

`import { readDirSync } from "node:fs"`

> LookedUpTypeFile: "@types/node/fs.d.ts/index.d.ts" was not sucessfully looked up

**Comment by lukasbach** [comment]
Hi @sasial-dev, I added some extra checks for node:xxx imports and it should now work as of 0.4.1.

**Comment by sasial-dev** [comment]
Thanks for that, but this still isn't fixed as while it detcets a node import, that won't work if the .d.ts file has a dependency import with `node:child_process`.
As shown from when I just checked in the playground:
<img width="446" alt="Brave Browser-PBsfe99P" src="https://user-images.githubusercontent.com/44125644/174515792-89607d71-3f99-4755-9edc-03bcb7da180a.png">

**Comment by lukasbach** [comment]
Oh my bad, I was missing something in the implementation. Can you check again in 0.4.2 if it is working now? Sorry for the back and forth, now it should be working 😅

**Comment by sasial-dev** [comment]
Yep, that's awesome - thanks!
